name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore Newtonsoft.Json/Newtonsoft.Json.csproj
    - name: Package
      run: dotnet pack Newtonsoft.Json/Newtonsoft.Json.csproj

