name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/fakutori/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore Newtonsoft.Json/Newtonsoft.Json.csproj
    - name: Package
      run: dotnet pack Newtonsoft.Json/Newtonsoft.Json.csproj
    - name: Publish
      run: dotnet nuget push Newtonsoft.Json/bin/Debug/Newtonsoft.Json.12.0.3.nupkg -s https://nuget.pkg.github.com/fakutori/index.json
